services:
  kafka:
#    image: 'maliksalman/kafka-dev:3.7.0'
    image: 'registry.lan.salmanmalik.me/maliksalman/kafka-dev:3.7.0-arm64'
    environment:
      - "ENABLE_KAFKA_UI=true"
      - "ADVERTISED_HOST=${LOCALNAME}"
    extra_hosts:
      - "${LOCALNAME}:127.0.0.1"
    ports:
      - '2181:2181'
      - '9092:9092'
      - '15000:8080'