springdoc:
  swagger-ui:
    path: /
spring:
  cloud:
    function:
      definition: pieReceived
    stream:
      default-binder: rabbit
      default:
        group: initiator
      bindings:
        apple:
          destination: apple-topic
        orange:
          destination: orange-topic
        pieReceived-in-0:
          destination: pie-topic