spring:
  main:
    web-application-type: none
  cloud:
    function:
      definition: orangeReceived;makeApplePie
    stream:
      default-binder: rabbit
      default:
        group: responder
      bindings:
        orangeReceived-in-0:
          destination: orange-topic
        makeApplePie-in-0:
          destination: apple-topic
        makeApplePie-out-0:
          destination: pie-topic
  docker:
    compose:
      file: ../compose-rabbit.yaml
      lifecycle-management: start_only
